"""Complete schema regeneration

Revision ID: a40cde67d3f9
Revises: 
Create Date: 2025-05-12 03:07:59.214127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a40cde67d3f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('dataset_identifier', sa.String(length=100), nullable=False),
    sa.Column('default_bandwidth_mbps', sa.Float(), nullable=True),
    sa.Column('default_latency_ms', sa.Integer(), nullable=True),
    sa.Column('scoring_function_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_problem_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_problem_title'), ['title'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'CONTESTANT', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('submission',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('algorithm_script_filename', sa.String(length=255), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'INITIALIZING', 'RUNNING', 'COMPLETED', 'FAILED', 'ERROR_STARTING', 'TIMEOUT', name='submissionstatus'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('log_filename', sa.String(length=100), nullable=True),
    sa.Column('actual_bandwidth_mbps', sa.Float(), nullable=True),
    sa.Column('actual_latency_ms', sa.Integer(), nullable=True),
    sa.Column('return_code', sa.Integer(), nullable=True),
    sa.Column('detailed_results', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_problem_id'), ['problem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submission_submitted_at'), ['submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_submission_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_user_id'))
        batch_op.drop_index(batch_op.f('ix_submission_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_submission_problem_id'))

    op.drop_table('submission')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_problem_title'))
        batch_op.drop_index(batch_op.f('ix_problem_created_at'))

    op.drop_table('problem')
    # ### end Alembic commands ###
